# Generated by Django 2.0.2 on 2018-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_auto_20180409_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='postcode',
            field=models.CharField(help_text='Enter company postcode', max_length=10, null=True),
        ),
    ]
