# Generated by Django 2.0.2 on 2018-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_auto_20180417_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='Enter description', help_text='Enter job description', max_length=1000),
            preserve_default=False,
        ),
    ]
