# Generated by Django 2.0.4 on 2018-05-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_jobquote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobQuote',
            new_name='Quote',
        ),
    ]
