# Generated by Django 2.0.4 on 2018-05-08 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_auto_20180502_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='closing_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enter ending date:'),
            preserve_default=False,
        ),
    ]
