# Generated by Django 2.0.2 on 2018-04-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, help_text='Enter job description', max_length=1000, null=True),
        ),
    ]
