# Generated by Django 2.0.2 on 2018-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004_auto_20180418_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='value',
            field=models.IntegerField(blank=True, help_text='Enter job value', null=True),
        ),
    ]
