# Generated by Django 2.0.2 on 2018-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_job_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
