# Generated by Django 2.0.2 on 2018-04-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prototype.Region'),
        ),
    ]
