# Generated by Django 2.0.4 on 2018-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_auto_20180514_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='trade',
            field=models.ManyToManyField(null=True, to='prototype.Trade'),
        ),
    ]
