# Generated by Django 2.0.2 on 2018-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_job_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Enter job description', max_length=1000, null=True),
        ),
    ]
