# Generated by Django 2.0.4 on 2018-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_auto_20180516_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='trade',
            field=models.ManyToManyField(to='prototype.Trade'),
        ),
    ]
