# Generated by Django 2.0.2 on 2018-04-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_auto_20180418_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Enter job description', max_length=750, null=True),
        ),
    ]
